site_name: "Advanced TiBasic  - Compiler Docs"
theme: "readthedocs"
pages: 
    - "index.md"
    - "tags.md"
    - "types.md"
    - "unsafe.md"
    - "files.md"
    - "Internals":
        - "internals/tokens.md"
        - "internals/ast.md"
    - "Python API":
        - "python-api/file-structure.md"
        - "python-api/Handling-Errors.md"
        - "tic":
            - "python-api/tic/TypeEnum.md"
            - "python-api/tic/Error.md"
            - "python-api/tic/ErrorHandler.md"
            - "python-api/tic/Type.md"
            - "python-api/tic/OutputMGR.md"
        - "ast":
            - "python-api/ast/NodeType.md"
            - "python-api/ast/NodeDebugInfo.md"
            - "python-api/ast/Node.md"
            - "python-api/ast/List.md"
            - "python-api/ast/Scope.md"
            - "python-api/ast/Number.md"
            - "python-api/ast/Function.md"
            - "python-api/ast/Program.md"
            - "python-api/ast/Unsafe.md"
            - "python-api/ast/FunctionParameter.md"
            - "python-api/ast/FunctionCall.md"
            - "python-api/ast/VariableDeclaration.md"
            - "python-api/ast/UnsafeVariable.md"
            - "python-api/ast/Variable.md"
            - "python-api/ast/Command.md"
